on: pull_request

jobs:
  test-coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Comment with Test Coverage
        uses: artiomtr/jest-coverage-report-action@v1.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          test_script: npm run test --silent --ci --coverage --json --coverageReporters="text" --coverageReporters="text-summary" --outputFile=\"report.json\"
